exports.SHOW_TABLES = 'SHOW TABLES IN `%s`';
exports.COMPARE_COLUMNS = "SELECT IF(GROUP_CONCAT(action ORDER BY action) = 'ADD,DROP','MODIFY',action) as action,column_name,ordinal_position,data_type,column_type FROM (SELECT column_name,ordinal_position,data_type,column_type,COUNT(1) as rowcount, IF(table_schema='%s', 'ADD', 'DROP') as action FROM information_schema.columns WHERE (table_schema='%s' OR table_schema='%s') AND table_name ='%s' GROUP BY column_name,data_type,column_type,table_name HAVING COUNT(1)=1)A GROUP BY column_name;";
exports.SWITCH_DB = "USE `%s`;";
exports.CHANGE_COLUMN = "ALTER TABLE %s CHANGE COLUMN %s %s;";
exports.ADD_COLUMN = "ALTER TABLE %s ADD COLUMN %s %s;";
exports.MODIFY_COLUMN = "ALTER TABLE %s MODIFY COLUMN %s %s;";
exports.DROP_COLUMN = "ALTER TABLE %s DROP COLUMN %s";
exports.COMPARE_TABLES = "SELECT table_name, IF(table_schema='%s','CREATE','DROP') as action from information_schema.tables where table_schema in('%s', '%s') group by table_name having count(1)=1";
exports.DROP_TABLE = "DROP TABLE `%s`;";
exports.RENAME_TABLE = "RENAME TABLE `%s` TO `%s`;";
exports.CREATE_TABLE = "CREATE TABLE `%s`.`%s` LIKE `%s`.`%s`;";