exports.SHOW_TABLES = 'SHOW TABLES IN `%s`';
exports.COMPARE_COLUMNS = "SELECT IF(GROUP_CONCAT(action order by action)='ADD,DROP','MODIFY',action) as action,column_name,ordinal_position,data_type,column_type FROM (SELECT column_name,ordinal_position,data_type,GROUP_CONCAT(column_type) as column_type,COUNT(1) as rowcount, IF(table_schema='%s', 'ADD', 'DROP') as action FROM information_schema.columns WHERE (table_schema='%s' OR table_schema='%s') AND table_name ='%s' GROUP BY column_name,column_type,table_name HAVING COUNT(1)=1 ORDER BY CASE WHEN table_schema = '%s' THEN '1' WHEN table_schema = '%s' THEN '2' END ASC)A group by column_name";
exports.SWITCH_DB = "USE `%s`;";
exports.CHANGE_COLUMN = "ALTER TABLE %s CHANGE COLUMN `%s` %s;";
exports.ADD_COLUMN = "ALTER TABLE %s ADD COLUMN `%s` %s;";
exports.MODIFY_COLUMN = "ALTER TABLE %s MODIFY COLUMN `%s` %s;";
exports.DROP_COLUMN = "ALTER TABLE %s DROP COLUMN `%s`";
exports.COMPARE_TABLES = "SELECT table_name, IF(table_schema='%s','CREATE','DROP') as action from information_schema.tables where table_schema in('%s', '%s') group by table_name having count(1)=1";
exports.DROP_TABLE = "DROP TABLE `%s`;";
exports.RENAME_TABLE = "RENAME TABLE `%s` TO `%s`;";
exports.CREATE_TABLE = "CREATE TABLE `%s`.`%s` LIKE `%s`.`%s`;";
exports.DROP_DATABASE = "DROP DATABASE `%s`";
exports.COMPARE_KEYS = "SELECT IF(GROUP_CONCAT(action order by action)='ADD,DROP','MODIFY',action) as action,table_name,index_name, non_unique, index_type, columns FROM ( SELECT index_type, table_name,index_name, non_unique, GROUP_CONCAT(column_name ORDER BY seq_in_index) AS `columns`, IF(table_schema='%s', 'ADD', 'DROP') as action FROM information_schema.statistics WHERE (table_schema='%s' OR table_schema='%s') AND table_name ='%s' GROUP BY index_name, index_type, non_unique, table_name HAVING COUNT(1)=COUNT(DISTINCT(column_name)) )A group by index_name;";
exports.ADD_PRIMARY = "ALTER TABLE `%s` ADD PRIMARY KEY ( `%s` );";
exports.DROP_PRIMARY = "ALTER TABLE `%s` DROP PRIMARY KEY;";
exports.MODIFY_PRIMARY = "ALTER TABLE `%s` DROP PRIMARY KEY , ADD PRIMARY KEY ( `%s` );";
exports.ADD_INDEX = "ALTER TABLE `%s` ADD %s INDEX `%s` ( `%s` );";
exports.DROP_INDEX = "ALTER TABLE `%s` DROP INDEX `%s`;";
exports.MODIFY_INDEX = "ALTER TABLE `%s` DROP INDEX `%s` , ADD %s INDEX `%s` ( `%s` );";